# Generated by Django 3.2.5 on 2021-08-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/Donor/'),
        ),
    ]
