# Generated by Django 3.2.5 on 2021-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_alter_donor_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('feed', models.TextField(max_length=500)),
            ],
        ),
    ]
