# Generated by Django 3.2.5 on 2021-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
            ],
        ),
    ]
